spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/ayman
    username: ayman
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


server:
  port: 8080
